### ISSUE TITLE
Enhancement: Tagging Volumes

### ISSUE THREAD

**Issue by norman-abramovitz** [jhunt/lkebot#1]
When looking at the disks it would be helpful if the volumes were tagged with which cluster(s) they were attached to.   This would make it clearer why those disks existed.

**Comment by jhunt** [comment]
It most certainly would, but that is a matter for LKE, not the robot.  lkebot is not involved in the day-to-day operation of the LKE clusters; just the spin-up and tear-down.  The disks you saw (in undisclosed, non-public conversations about "the event") are created _by_ the LKE CSI, not the bot.

And trust me, you do NOT want an automated bot deleting all unattached volumes in a Linode account, all willy-nilly.
